### ISSUE TITLE
NotifyDataSetChanged Problem

### ISSUE THREAD

**Issue by hearsilent** [AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller#10]
If I use `notifyDataSetChanged()` the bubble text and handle position is wrong.

**Comment by AndroidDeveloperLB** [comment]
hmmm....
Try to call "setRecyclerView" before each time you call notifyDataSetChanged() .
I don't know if this will help.

**Comment by hearsilent** [comment]
Thx, this is work!

**Comment by AndroidDeveloperLB** [comment]
sorry for that. there should be a better way, but it will work fine I think.

**Comment by AndroidDeveloperLB** [comment]
@hearsilent Now that I think about it, I think using the function is problematic, as it adds the same listener again and again. 
I need to change it.

**Comment by hearsilent** [comment]
@AndroidDeveloperLB Got it! Maybe you can extract `recyclerView.getViewTreeObserver().addOnPreDrawListener`.

Tell me if you updated code, thx.

**Comment by AndroidDeveloperLB** [comment]
@hearsilent Done !

**Comment by AndroidDeveloperLB** [comment]
oops i caused it to crash. will fix it soon.

**Comment by AndroidDeveloperLB** [comment]
ok , now fixed. :)

**Comment by hearsilent** [comment]
Got it! Thx!
