### ISSUE TITLE
Resolved 2 of the TODO points

### ISSUE THREAD

**Issue by davideas** [AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller#13]
Hello @AndroidDeveloperLB, currently (as you know) I'm using your base FastScroller in my [FlexibleAdapter](https://github.com/davideas/FlexibleAdapter) library.
I don't know if I will continue to keep your base FastScroller or to change to another one, however, it now works when changing LayoutManager (switching from Linear to Grid and viceversa) and also with `GridLayoutManager` (probably it always worked with Grid).

In my version you will find more features: I had to customize it and improve it in order to fit in combination the adapter animations and beyond. Details are in my [code](https://github.com/davideas/FlexibleAdapter/blob/dev/flexible-adapter/src/main/java/eu/davidea/fastscroller/FastScroller.java).

Maybe if we work together we can add some nice features like the library I have found (see my [issue](https://github.com/davideas/FlexibleAdapter/issues/34)).

**Comment by AndroidDeveloperLB** [comment]
I have actually never tried. Please do a pull request if you can. I wish to make this library as minimal as possible, yet work well.
