### ISSUE TITLE
Theres a big issue with the scrolling 

### ISSUE THREAD

**Issue by lamdanAmiti** [AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller#21]
@AndroidDeveloperLB `אני באמת צריך ליצור איתך קשר לגבי עבודה מרכזית, אנא שלח לי דוא"ל לכתובת psslesd1@gmail.com`

**Comment by AndroidDeveloperLB** [comment]
Contact me directly via private messaging on reddit, XDA, or email.
Here it's not the place.
