### ISSUE TITLE
Can you clarify the license of your code?

### ISSUE THREAD

**Issue by shaiay** [AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller#5]
Thanks for the excellent code. 
Can you clarify the license so that I can understand if it's OK to use?

Shai

**Comment by shaiay** [comment]
Just saw the LICENSE file. duh!

**Comment by AndroidDeveloperLB** [comment]
You can do what you wish with it. 
It would be nice to have the repo mentioned on the credits/thanks page though. :)
