### ISSUE TITLE
Scrolling behaviour when using AppBar layout or scrolling tabs

### ISSUE THREAD

**Issue by dhaval0122** [AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller#8]
Please update sample which work with design support library behaviour, when use fastscroll with recycleview its stop behaviour of autoscroll AppBar and Tabs

**Comment by AndroidDeveloperLB** [comment]
Sorry for that, but the sample was created before the design library was even introduced.
I will keep this issue open till this will be fixed.
If there is an issue, and you've found how to fix it, please let me know.

**Comment by AndroidDeveloperLB** [comment]
I've separated the sample and the library, and added some code to show how to use along with the design library.

Some of the code is based on this repo:
https://github.com/sitepoint-editors/Design-Demo
