### ISSUE TITLE
Handling collapse/expand of AppBarLayout in CoordinatorLayout?

### ISSUE THREAD

**Issue by TheNephilim88** [AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller#9]
Hey,

is it anyhow possible to let appbarlayout collapse or expand depending on how the fastscroller is moved to? (Collapsing when scrolling down the list, expanding when scrolling up)

Usually this will happen in RecyclerView automatically when scrolling up/down.

**Comment by AndroidDeveloperLB** [comment]
I have no idea. My guess is that it's possible.
If you need something, and make a contribution here, I would be happy to
accept it into the repo. Just try to make it general enough for other
developers. I know I could have done it better, but this is what I needed
for a project I worked on.

**Comment by AndroidDeveloperLB** [comment]
You succeeded?

**Comment by TheNephilim88** [comment]
Yes and no.

Calling recyclerView's onTouchEvent in RecyclerViewFastScroller's onTouchEvent will make collapsing and expanding of toolbar work.

Nonetheless its not really perfect. E.g. if you are on bottom of a list (where toolbar is collapsed) and then go up with the fastscroller, then its a bit "jumpy". You know, if you are at index Z and want to go to Y, then toolbar expands, which lead to reposition of the fastscrollbar (the fastscroller-view gets moved a bit down) and so current selected index isnt Y anymore, but for example X. (Dont know if this is understandable ^^)

So if anyone has an idea how to get this smoother, I would be happy to hear about them :)

**Comment by AndroidDeveloperLB** [comment]
I suggest doing it like on the contacts app : don't change the toolbar at all when dragging the fast-scroller.
I know it's not what I did on the sample. It was a quick change and I didn't have enough time to make it work nicely. Sorry about that.
